easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Vehicle
        - App\Entity\VehicleModel
        - App\Entity\VehicleProducer
